server:
  port: 9000

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: #eureka.url#
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000