spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
        serialization.write_dates_as_timestamps: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.5:3306/pangolin_business?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: mysql
        password: mysql
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    rabbitmq:
        username: cuidaren
        password: CuiDaRen!23456
        host: 172.19.28.135
        virtual-host: cuidaren
        port: 5672

eureka:
  instance:
    hostname: file-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://172.19.28.135:8761/eureka/
server:
    port: 9001

cuibei:
  baiduMap:
    webUrl: http://api.map.baidu.com/place/v2/search?region=全国&ak=
    webAk: lHaYCXlRADlhW0fnv8tpIhCfqD85pTSr
