spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.3.10:3306/pangolin_business_classic?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: mysql
        password: mysql
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            maximumPoolSize: 50
    rabbitmq:
        username: classic
        password: classic
        host: 192.168.3.10
        virtual-host: classic
        port: 5672

    cache:
        jcache:
            config: ehcache.xml
    redis:
        database: 5
        host: 192.168.3.10
        port: 6379
        expireTime: 3600
        password: pangolinRedis


eureka:
  instance:
    hostname: business-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 9001

cuibei:
  baiduMap:
    webUrl: http://api.map.baidu.com/place/v2/search?region=全国&ak=
    webAk: lHaYCXlRADlhW0fnv8tpIhCfqD85pTSr

threadPool:
   corePoolSize: 10
   maxPoolSize: 200
   keepAliveSeconds: 60
   queueCapacity: 500
   allowCoreThreadTimeout: false
   threadNamePrefix: pangolin-
