spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    data:
        mongodb:
            uri: mongodb://192.168.1.5:27017
            database: file_db
    rabbitmq:
        username: dev
        password: dev
        host: 192.168.1.6
        virtual-host: dev
        port: 5672

eureka:
  instance:
    hostname: business-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 9012
