spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.3.10:3306/pangolin_business?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: pangolin
        password: Pangolin123!
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

eureka:
  instance:
    hostname: report-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 9006

threadPool:
  corePoolSize: 5
  maxPoolSize: 50
  keepAliveSeconds : 60
  queueCapacity: 100
  threadNamePrefix: pangolin-



